### PR TITLE
Fixes from science-parse

### PR DESCRIPTION
**Pull request by dirkgr**
SP has accumulated some fixes that aren't here, so I'm putting them here.

### CODE REVIEW

**Comment by dirkgr** [comment]
Ehh, I can't assign reviewers, or edit anything?

**Comment by dirkgr** [comment]
> Can you run evaluation to make sure everything still works?

I'm on it.

**Comment by dirkgr** [comment]
```Precision: 0.980, Recall: 0.960, F1: 0.970```

**Comment by siegeln** [comment]
Could you also run on the s2 dataset? Just want to make sure there aren't any unexpected changes from https://github.com/allenai/pdffigures2/pull/2.

**Comment by dirkgr** [comment]
On S2:
```Precision: 0.943, Recall: 0.908, F1: 0.925```

**Comment by dirkgr** [comment]
I also confirmed that `master` dies on my cartesian-product poison document, and this version does not. In fact, this one finishes in 10 seconds (but produces no figures for the affected pages).

**Pull request merged**
